CREATE TABLE TOPIC
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IMAGE_NAME NTEXT,
	TOPIC_NAME TEXT
)

CREATE TABLE SUBTOPIC
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IMAGE_NAME NTEXT,
	SUBTOPIC_NAME TEXT,
	TOPIC_ID INT,
	FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC(ID)
)

CREATE TABLE CARD
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	QUESTION_CATE INT, -- 1. TRAC NGHIEM 2. DIEN 3. MULTI CHOICE
	QUESTION TEXT,
	SUBTOPIC_ID INT,
	FOREIGN KEY (SUBTOPIC_ID) REFERENCES SUBTOPIC(ID)
)

CREATE TABLE ANSWER
(
	CARD_ID INT,
	ANSWER_ID INT,
	ANSWER_TEXT TEXT,
	IS_TRUE BIT,
	PRIMARY KEY(CARD_ID, ANSWER_ID),
	FOREIGN KEY(CARD_ID) REFERENCES CARD(ID)
)

-- CHI LUU NHUNG CAU HOI DA CAM THAY NHO
CREATE TABLE PLAY_HISTORY
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TIME_HISTORY DATETIME
)

CREATE TABLE HISTORY_CARD_TOPIC_PLAY
(
	SUBTOPIC_ID INT,
	CARD_ID INT,
	PLAY_HISTORY_ID INT,
	IS_TRUE BIT,
	PRIMARY KEY(SUBTOPIC_ID, CARD_ID, PLAY_HISTORY_ID),
	FOREIGN KEY (SUBTOPIC_ID) REFERENCES SUBTOPIC(ID),
	FOREIGN KEY (CARD_ID) REFERENCES CARD(ID),
	FOREIGN KEY (PLAY_HISTORY_ID) REFERENCES PLAY_HISTORY(ID)
)

INSERT INTO TOPIC(TOPIC_NAME) VALUES(N'Nhập môn lập trình'),
	(N'Lập trình hướng đối tượng'), 
	(N'Cấu trúc dữ liệu và giải thuật'), 
	(N'Lập trình Windows và đồ án môn học'),
	(N'Phân tích thiết kế hệ thống'),
	(N'Ngôn ngữ Java'),
	(N'Cơ sở dữ liệu'),
	(N'Hệ quản trị cơ sở dữ liệu')


INSERT INTO SUBTOPIC(TOPIC_NAME, TOPIC_ID) 
		VALUES(N'WINDOWS FORM', 4),
			(N'ADO.NET', 4),
			(N'REPORT', 4),
			(N'FORM VÀ CONTAINER', 4),
			(N'CÁC CONTROL CƠ BẢN', 4),
			(N'TIMER, DIALOG', 4),
			(N'ỨNG DỤNG MDI', 4),
			(N'TỔNG QUAN VỀ CƠ SỞ DỮ LIỆU',8),
			(N'MÔ HÌNH DỮ LIỆU QUAN HỆ',8),
			(N'MÔ HÌNH THỰC THỂ - KẾT HỢP',8),
			(N'ĐẠI SỐ QUAN HỆ',8),
			(N'NGÔN NGỮ TRUY VẤN SQL',8),
			(N'USECASE DIAGRAM', 5),
			(N'ACTIVITY DIAGRAM', 5),
			(N'SEQUENCE DIAGRAM', 5),
			(N'ERD', 5),
			(N'CLASS DIAGRAM', 5)

INSERT INTO CARD(LEVEL, CORRECT_ANSWERT, QUESTION_CATE, QUESTION, TIME, SUBTOPIC_ID)
VALUES (),()


		